FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["DirectServer/DirectServer.csproj", "DirectServer/"]
COPY ["Contracts/Contracts.csproj", "Contracts/"]
RUN dotnet restore "DirectServer/DirectServer.csproj"

COPY . .
RUN dotnet publish -c Release -o /app DirectServer/DirectServer.csproj 

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS publish
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "DirectServer.dll"]
