FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["DirectClient/DirectClient.csproj", "DirectClient/"]
COPY ["Contracts/Contracts.csproj", "Contracts/"]
RUN dotnet restore "DirectClient/DirectClient.csproj"

COPY . .
RUN dotnet publish -c Release -o /app DirectClient/DirectClient.csproj 

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS publish
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "DirectClient.dll"]
